/*
 * Copyright Institute for Theoretical Physics, ETH Zurich 2015.
 * Distributed under the Boost Software License, Version 1.0.
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer,
 * must be included in all copies of the Software, in whole or in part, and
 * all derivative works of the Software, unless such copies or derivative
 * works are solely in the form of machine-executable object code generated by
 * a source language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

#ifndef BIND_MODEL_HISTORY
#define BIND_MODEL_HISTORY

#include "bind/utils/dim2.hpp"

// revision tracking mechanism (target selector)
namespace bind { namespace model {

    class history : public memory::cpu::use_fixed_new<history> {
    public:
        history(dim2 dim, size_t ts) : current(NULL), dim(dim), extent(bind::memory::aligned_64(dim.square()*ts)) { }
        void init_state(rank_t owner){
            revision* r = new revision(extent, NULL, locality::common, owner);
            this->current = r;
        }
        template<locality L> void add_state(functor* gen, rank_t owner){
            revision* r = new revision(extent, gen, L, owner);
            this->current = r;
        }
        revision* back() const {
            return this->current;
        }
        bool weak() const {
            return (this->back() == NULL);
        }
        revision* current;
        size_t extent;
        dim2 dim;
    };

} }

#endif
