# Makefile for cpu/node examples

CXX = mpiicpc
FLAGS = -O3 -std=c++11 -mt_mpi -DBIND_REQUIRE_MPI
EXAMPLES = diffusion.node max_rank.node

.DEFAULT: all
.PHONY: all clean
all: $(EXAMPLES)

%.node: %.cpp
	$(CXX) -o $@ $< $(FLAGS)

clean:
	-rm -f $(EXAMPLES)
