# Makefile for cpu single-node examples

CXX = icpc
FLAGS = -O3 -std=c++11
EXAMPLES = array shared_ptr reduce diffusion

.DEFAULT: all
.PHONY: all clean
all: $(EXAMPLES)

%: %.cpp
	$(CXX) -o $(basename $<) $< $(FLAGS)

clean:
	-rm -f $(EXAMPLES)
